### ISSUE TITLE
Canvas绘制矩形的一点疑问

### ISSUE THREAD

**Issue by peerless2012** [GcsSloop/AndroidNote#22]
mPaint.setColor(Color.YELLOW);
    mPaint.setStyle(Style.STROKE);
    canvas.translate(centerX, centerY);
    mPaint.setStrokeWidth(3);
    canvas.drawRect(0, 0, 200, -200, mPaint);//笔记中的写法,没有效果	
    mPaint.setColor(Color.RED);
    canvas.drawRect(0, -200, 200, 0, mPaint);//有效果,在预定的坐标系原点右上角

**Comment by GcsSloop** [comment]
(⊙o⊙)…发生了灵异现象，所有代码都经过测试居然还能出现这样的事情:joy: 猜测是support问题。我去原工程重新看了一下，只需要指定矩形**任意对角线的两个点**就能画出一个矩形，然而新建工程之后就只有指定矩形**左上角和右下角**才可以，否则不显示。

**建议：以后绘制矩形只指定左上角和右下角，如果是将矩形封装为Rect或RectF可在绘制之前调用Rect的sort方法，也能解决问题。**

我去改文章了:joy:

**Comment by peerless2012** [comment]
用PictureDrawable 包装Picture的时候碰到一个比较困惑的问题.
设置Picture宽高是View宽高,然后再中心画一个圆,半径30,

- 如果 setBound(0,0,Width,height)或者setBound(0,0,Width/2,height/2),一个显示完整,一个显示左上四分之一,没问题

- 如果 setBound(Width/2 - 50 ,height/2 - 50,Width / 2 + 50,Width / 2 + 50),却找不到中心的圆

经过测试发现:

- Picture画出来的内容距离本View坐标系偏移了上述Boundleft和top

- Picture画出来的内容永远是从Picture左上角开始,并不像我想的可以自定义任意矩形

那么问题来了,如果我想截取非左上角开始的某个矩形区域绘制上去,则么破?

**Comment by peerless2012** [comment]
另外 绘制文字的时候 y 方向上的值不是文字的上边界,是文字的基准线.

**Comment by GcsSloop** [comment]
Picture的setBound(设置边界)，是指设置绘制时的边界，例如设置(100,100,200,200)是指定画布中(100,100,200,200)这个矩形区域为绘制区域，并非是从Picture中截取(100,100,200,200)这个区域然后绘制到画布(0,0,100,100)这个区域上。文章中有歧义:astonished:。如果想截取一部分绘制，可以先将Picture内容绘制到Canvas上，然后将Canvas转换为Bitmap进行操作。

文字那一部分的确是基准线:joy:，是我失误了，文字操作部分也是慢多了，后面补吧。

提交这么多建议，辛苦了。

**Comment by peerless2012** [comment]
感觉如果想绘制Picture的一部分好麻烦...

最近想自己去绘制影院选座的控件，所以打算先把Canvas的内容完整过一遍。

今天过第五部分的内容，发现两个问题：
    
- 绘制矩形，起点是在左上角，而不是右下角。
- 绘制矩形路径的时候发现 addRoundRect(rect, radii, dir)这个方法,在第二个参数去指定各个角的圆角参数,不管你设置的是CW还是CCW,指定的都是从左上角顺时针的圆角值,不知我测试的结果是否正确.

**Comment by GcsSloop** [comment]
我测试两者还是有区别的，但是圆角矩形的控制点是8个，并不知道圆角矩形是怎么计算第一个控制点的。

**Comment by peerless2012** [comment]
不要反转坐标系,float[] cs = new float[]{0,0,15,15,25,25,35,35}; ,不管选择的是CW还是CCW都是一样的我看到的圆角大小一致都是从左上角 顺时针变大.刚开始我也以为是自己错了,还怀疑预览错了,发布到手机上也是同样的效果.

**Comment by GcsSloop** [comment]
加我微信 好Github同名

**Comment by peerless2012** [comment]
Path内容中
- set方法,代码是reSet
- offset 方法第三个参数写反了

**Comment by GcsSloop** [comment]
笔误:sweat:

**Comment by peerless2012** [comment]
啥时候继续更新啊? 已经过完了

**Comment by GcsSloop** [comment]
下周结束之前更下一篇:joy_cat:
