### ISSUE TITLE
角度与弧度的换算问题

### ISSUE THREAD

**Issue by cocoas** [GcsSloop/AndroidNote#26]
应该是 1角度=π弧度/180  。1弧度=180度/π。
好像是写反了，另外感谢您的教程。

**Comment by GcsSloop** [comment]
公式应该是没有问题的。

公式 | 例子
---|---
弧度 = 角度xπ/180 | 2π ＝ 360 x π / 180 
角度 = 弧度x180/π | 360 ＝ 2π x 180 / π
