### ISSUE TITLE
弧度和角度的转换公式貌似写完了

### ISSUE THREAD

**Issue by xiaohao890809** [GcsSloop/AndroidNote#27]
如题，弧度和角度的转换公式貌似写反了

**Comment by GcsSloop** [comment]
你说的是 基础篇－角度弧度 这篇文章么？

弧度的维基百科 －> https://zh.wikipedia.org/wiki/%E5%BC%A7%E5%BA%A6

**Comment by xiaohao890809** [comment]
恩，，前面的是对的，就是得出的公式反了
故: 180度 = π弧度.
应该是可得:
弧度 = 角度x180/π
角度 = 弧度xπ/180

**Comment by GcsSloop** [comment]
圆一周是 2π弧度， 360度

公式 | 例子
---|---
弧度 = 角度xπ/180 | 2π ＝ 360 x π / 180 
角度 = 弧度x180/π | 360 ＝ 2π x 180 / π

???

**Comment by GcsSloop** [comment]
确实写反了

**Comment by GcsSloop** [comment]
不对啊，你在哪里看的？？？

**Comment by xiaohao890809** [comment]
就是在你的 基础篇－角度弧度 这篇文章哦，[https://github.com/GcsSloop/AndroidNote/blob/master/CustomView/Base/[2]AngleAndRadian.md](url)

**Comment by GcsSloop** [comment]
什么鬼，下面是我的截图

![](http://ww2.sinaimg.cn/large/005Xtdi2gw1f4hu9b0hmlj30c105yaai.jpg)

**Comment by xiaohao890809** [comment]
恩，如果我没有说错的话，你的结论是写错了，你再仔细看一下你的结论。

**Comment by GcsSloop** [comment]
你看到的和我给你发的截图一样么

**Comment by xiaohao890809** [comment]
恩，我看到的就是发的截图的样子

**Comment by GcsSloop** [comment]
那应该是对的啊， 这是维基百科的公式

>  rad 是弧度， deg 是角度

![](http://ww3.sinaimg.cn/large/005Xtdi2jw1f4hui2jaecj305m03lwee.jpg)
