### ISSUE TITLE
Android studio 编译ndk 不能生成so文件的问题

### ISSUE THREAD

**Issue by xinzy** [GcsSloop/AndroidNote#33]
第一次使用android studio 编译ndk，
建立src/main/jni目录，编写c代码，
之后在build.gradle里添加ndk 配置
 android  {
     ndk {
            moduleName "HelloJNI"
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
}
sourceSets {
        main {
            jni.srcDirs = ["jni"]
        }
    }
怎么也不能编译出so文件，google搜索了好久，也没找到相应的答案
似乎Google上很少有人不能编译出so文件的，但我就是编译不出来，也不报错误
不知道有没有解决方案

**Comment by GcsSloop** [comment]
非常抱歉，这一部分我不太熟悉，建议先检查一下androidstudio ndk编程的基本配置，https://dailyios.com/article/Using_Android_Studio_for_NDK_development.html

**Comment by xiaotongCat** [comment]
sourceSets {
main {
jni.srcDirs = ["jni"]
} 应该在Android的大括号 里，不是外面
