### ISSUE TITLE
作者是否考虑讲解Android 的压感绘图

### ISSUE THREAD

**Issue by tianshaokai** [GcsSloop/AndroidNote#40]
现在的手机 平板屏幕都已经支持了触摸笔，支持压感绘图（我说的效果其实就是在屏幕上写毛笔字），显示出来笔锋效果，我查过资料 有一些api 没看明白，希望作者讲解一下，让大家都学习一下最好可以配上简单的demo

**Comment by jaydenxiao2016** [comment]
好，有空写个文章

**Comment by GcsSloop** [comment]
好的
