### ISSUE TITLE
onDraw方法for循环内无法画图，但循环确实执行了（提问人：魔法师的学徒）

### ISSUE THREAD

**Issue by dc1998** [GcsSloop/AndroidNote#45]
**// 大哥，我这代码超简单的，就像我之前说的那样，每一块儿都是照着你的写的，不过就是简化了一下。您帮忙看看~~~ THX！！！

package com.example.administrator.piedraw;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.util.AttributeSet;
import android.util.Log;
import android.view.View;

import java.util.ArrayList;

/**
 * Created by Administrator on 2016/9/20.
 */
public class PieView extends View {
    private Paint mPaint=new Paint();
    private Color mColor=new Color();
    private float currentAngle=0;
    private float startAngle=0;
    private float mValue=0;
    private int mWidth,mHight;

    ArrayList<PieData> pieList=new ArrayList<PieData>();

    int[] colorList={0xFFCCFF00, 0xFF6495ED, 0xFFE32636, 0xFF800000, 0xFF808000, 0xFFFF8C69, 0xFF808080,
            0xFFE6B800, 0xFF7CFC00};

    int[] valueList={1,2,3,4,5,6,7,8};
    public PieView(Context context){
        super(context);
    }
    public PieView(Context context,AttributeSet attrs){
        super(context,attrs,0);
        mPaint.setStyle(Paint.Style.FILL);
        mPaint.setAntiAlias(true);

    }
    @Override
    public void onSizeChanged(int w,int h,int oldW,int oldH){
        mWidth=w;
        mHight=h;

    }
    @Override
    public void onDraw(Canvas canvas){

        mPaint.setColor(Color.GRAY);
        canvas.translate(mWidth/2,mHight/2);
        float r=(float)(Math.min(mWidth,mHight)/2*0.8);
        RectF rectF=new RectF(-r,-r,r,r);
        initialPieData(pieList);
        Log.d("PieView","onDraw is been excute------------------");

        for(int i=0;i<pieList.size();i++){
            Log.d("PieView","pie is been draw------------------------");
            PieData pieData=pieList.get(i);
            currentAngle=pieData.getAngle();
            mPaint.setColor(pieData.getColor());
            canvas.drawArc(rectF,startAngle,currentAngle,true,mPaint);
            startAngle+=currentAngle;
        }
    }
    public void initialPieData(ArrayList<PieData> pieList){
        int totalValue=0;
        for(int i=0;i<valueList.length;i++) {
            totalValue += valueList[i];
        }
        for(int i=0;i<8;i++){
            Log.d("PieView","initialPieData is been excute---------------------");
            PieData pieData=new PieData();
            pieData.setColor(colorList[i]);
            int value=valueList[i];
            float startAngle=value/totalValue*360;
            pieData.setAngle(startAngle);
            pieList.add(pieData);

        }
    }
}

**Comment by GcsSloop** [comment]
取值精度太低，`float startAngle = value / totalValue * 360;`中startAngle按照你的数值计算结果都是0
将数值精度从int改为float。
另外不要在onDraw里面初始化数据，会重复初始化，影响性能。

``` java
public class PieViewTest extends View {
    private Paint mPaint = new Paint();
    private Color mColor = new Color();
    private float currentAngle = 0;
    private float startAngle = 0;
    private float mValue = 0;
    private int mWidth, mHight;

    ArrayList<PieData> pieList = new ArrayList<PieData>();

    int[] colorList = {0xFFCCFF00, 0xFF6495ED, 0xFFE32636, 0xFF800000, 0xFF808000, 0xFFFF8C69, 0xFF808080,
            0xFFE6B800, 0xFF7CFC00};

    float[] valueList = {1, 2, 3, 4, 5, 6, 7, 8};

    public PieViewTest(Context context) {
        this(context, null);
    }

    public PieViewTest(Context context, AttributeSet attrs) {
        super(context, attrs, 0);
        mPaint.setStyle(Paint.Style.FILL);
        mPaint.setColor(Color.GRAY);
        mPaint.setAntiAlias(true);
        initialPieData(pieList);

    }

    @Override
    public void onSizeChanged(int w, int h, int oldW, int oldH) {
        mWidth = w;
        mHight = h;

    }

    @Override
    public void onDraw(Canvas canvas) {


        canvas.translate(mWidth / 2, mHight / 2);
        float r = (float) (Math.min(mWidth, mHight) / 2 * 0.8);
        RectF rectF = new RectF(-r, -r, r, r);

       // Log.d("PieView", "onDraw is been excute------------------");

        for (int i = 0; i < pieList.size(); i++) {

            PieData pieData = (PieData) pieList.get(i);
            currentAngle = pieData.getAngle();
            mPaint.setColor(pieData.getColor());
            canvas.drawArc(rectF, startAngle, currentAngle, true, mPaint);
            startAngle += currentAngle;
            Log.e("PieView", "currentAngle"+currentAngle+": startAngle"+startAngle+" :"+pieData.getColor());
        }
    }

    public void initialPieData(ArrayList pieList) {
        float totalValue = 0;
        for (int i = 0; i < valueList.length; i++) {
            totalValue += valueList[i];
        }
        for (int i = 0; i < 8; i++) {
           // Log.d("PieView", "initialPieData is been excute---------------------");
            PieData pieData = new PieData();
            pieData.setColor(colorList[i]);
            float value = valueList[i];
            float startAngle = value / totalValue * 360;
            Log.e("Test", "startAngle:"+startAngle);
            pieData.setAngle(startAngle);
            pieList.add(pieData);

        }
    }
}
```

**Comment by dc1998** [comment]
！！！我四不四弱智？？？我去试试！！
