### ISSUE TITLE
转载

### ISSUE THREAD

**Issue by ouyangzn** [GcsSloop/AndroidNote#46]
大神我转载了你一篇文章
[程序员需要了解的版权协议](https://github.com/GcsSloop/AndroidNote/blob/magic-world/ChaosCrystal/%E5%BC%80%E6%BA%90%E5%85%B1%E4%BA%AB%E5%8D%8F%E8%AE%AE.md)
转载地址为：
[版权问题相关](https://github.com/ouyangzn/training/blob/master/%E7%89%88%E6%9D%83%E9%97%AE%E9%A2%98%E7%9B%B8%E5%85%B3.md)
如有问题请联系，谢啦

**Comment by GcsSloop** [comment]
如果是作为项目的开源协议，建议在README文字中声明一下。
