### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by OHoussein** [GcsSloop/AndroidNote#52]
Can you please translate this to english, I think it's very interesting :).

**Comment by GcsSloop** [comment]
This repositories have some essay about android custom view and others.
it‘s just some experience of my study and work，like a blog.
Most of the knowledge comes from [AndroidDeveloper](https://developer.android.com/develop/index.html).
I think the official documents may be more useful to you.

Thanks you for sending this message, I am very happy. ^_^
but I'm sorry I can not fulfill your request.
