### ISSUE TITLE
在Canvas上如何画一层文字并让它始终保持在最上层

### ISSUE THREAD

**Issue by 328629033** [GcsSloop/AndroidNote#70]
如题，由于文字下边一部分区域需要做重绘实现滑动效果，但重绘的时候并不想在重绘一遍文字（原谅我有强迫症），如果让文字始终保持在最上层呢？

**Comment by GcsSloop** [comment]
将文字单独绘制一层试试，用 canvas 的 layer。

虽说如此，但文字实际上还是会被重绘的，因为屏幕显示最终只有一层，不论多少层叠加，最终只能用一层显示。
所以看似是只有下层进行了刷新，实际上是刷新后，重新计算叠加值，最终显示，所以效率并不会提高。

如果只是下层滑动，上层位置不变的话，用 FrameLayout 就好了，不必自定义控件。
