### ISSUE TITLE
matrix原理简介

### ISSUE THREAD

**Issue by RuijiePan** [GcsSloop/AndroidNote#73]
matrix原理简介下出现

“Matrix是一个矩阵，主要功能是坐标映射，数值转换。

它看起来大概是下面这样:

![](http://latex.codecogs.com/png.latex?$$ \left [ \begin{matrix} MSCALE\_X & MSKEW\_X & MTRANS\_X \\ \ MSKEW\_Y & MSCALE\_Y & MTRANS\_Y \\ \ MPERSP\_0 & MPERSP\_1 & MPERSP\_2 \end{1} \right ] $$)”。图片链接有问题

**Comment by GcsSloop** [comment]
应该是 GitHub 更新了 Markdown 转换器导致的，之前直接写的公式不识别了，现在已经全部换成图片了。
