### ISSUE TITLE
发现小笔误一个

### ISSUE THREAD

**Issue by WangChangQin** [GcsSloop/AndroidNote#74]
在讲解path的那一章，moveTo只改变下次操作的起点，在执行完第一次LineTo的时候，本来的默认点位置是A(200,200),但是moveTo将其改变成为了C(200,100),所以在第二次调用lineTo的时候就是连接C(200,100) 到 B(200,0) 之间的直线(用蓝色圈2标注)。

应该为但是setLastPoint 将其改变了吧

**Comment by GcsSloop** [comment]
感谢反馈，我检查一下。

**Comment by GcsSloop** [comment]
这个应该是没有问题的，文字描述的是上面的图片和代码。
