### ISSUE TITLE
从维基百科上粘下来的弧度与角度的转化公式有误

### ISSUE THREAD

**Issue by abneryan** [GcsSloop/AndroidNote#80]

**Comment by GcsSloop** [comment]
计算验证过了吗？

**Comment by abneryan** [comment]
角度弧度的对应关系应该是错了

**Comment by GcsSloop** [comment]
如果你是参考的百度百科这篇文章或者类似的内容 http://baike.baidu.com/item/%E5%BC%A7%E5%BA%A6%E5%88%B6/3315973
![](https://ww1.sinaimg.cn/large/006tKfTcgy1fhfvlxbtm8j30nb08p765.jpg)

### 通过这个上面的表达式貌似可以得出 PI/180 * rad = deg，但这是错误的，因为最后面的那个是单位。

![](https://ww4.sinaimg.cn/large/006tKfTcgy1fhfvnu8f90j30nb08p76a.jpg)
![](https://ww3.sinaimg.cn/large/006tKfTcgy1fhfvr6csmnj30mj05hdie.jpg)

## 上面只是表示一种换算关系，并且单位不应该参与运算，例如 1m = 100cm 你不能说 m = 100/m*cm 或者 cm = 1/cm*m 。
## 如果不相信，可以根据这样推算出来的公式，在两边分别代入具体的数值，看是等式两边内容是否真的相等。

**Comment by abneryan** [comment]
☺谢谢你的细心解答，现在明白了，谢谢！

在 2017年7月11日 下午1:51，sloop <notifications@github.com>写道：
