### ISSUE TITLE
一个仓库多个lib，生成多个依赖，是怎么实现的

### ISSUE THREAD

**Issue by wmjwmj828** [GcsSloop/AndroidNote#93]
像RxLifecycle这样
我想提供多个依赖，别人可以选择性的使用其中的1个或多个，用jitpack我只能生成一个
![zh n tr_cmvd7 q81m7bhi](https://user-images.githubusercontent.com/31396243/48047119-f6cf5f00-e1d1-11e8-9395-f0a2a0abff5f.png)
![5_ g25c5i k1 xv ov rky](https://user-images.githubusercontent.com/31396243/48047122-fafb7c80-e1d1-11e8-8978-c696505f7d7e.png)

**Comment by GcsSloop** [comment]
我现在用自建仓库了，jitpack 虽然方便，但是就像你说的这样，存在一些标准仓库没有的限制。

**Comment by wmjwmj828** [comment]
请问你是用什么自建仓库哦

**Comment by wmjwmj828** [comment]
好的，谢谢！
