### ISSUE TITLE
camera 神奇 数值 72

### ISSUE THREAD

**Issue by caizhixing** [GcsSloop/AndroidNote#98]
感谢 博主的教程 关于[安卓自定义View进阶-Matrix Camera](http://www.gcssloop.com/customview/matrix-3d-camera)这篇文章 关于数值72的疑惑
>摄像机的位置默认是 (0, 0, -576)。其中 -576＝ -8 x 72，虽然官方文档说距离屏幕的距离是 -8, 但经过测试实际距离是 -576 像素，当距离为 -10 的时候，实际距离为 -720 像素。不过这个数值72我也不明白是什么东西，我使用了3款手机测试，屏幕大小和像素密度均不同，但结果都是一样的，知道的小伙伴可以告诉我一声。

正巧我前几天看了[安卓自定义View进阶-Matrix Camera](http://www.gcssloop.com/customview/matrix-3d-camera) 中[扔物线](https://github.com/rengwuxian)的对72数值的解释：
>这种设计源自 Android 底层的图像引擎 Skia 。在 Skia 中，Camera 的位置单位是英寸，英寸和像素的换算单位在 Skia 中被写死为了 72 像素，而 Android 中把这个换算单位照搬了过来。是的，它。写。死。了

**Comment by GcsSloop** [comment]
谢谢回复，稍后我更新一下。
